apiVersion: v1
kind: Service
metadata:
  name: demo-api-service
  labels:
    app: demo-api
spec:
  selector:
    app: demo-api
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP